version: '3.8'

services:
  app: 
    build: 
      context: .
    ports:
      - '3000:3000'
    depends_on:
      redis:
        condition: 
          service_healthy
      mongo:
        condition:
          service_healthy
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:ieWVvARzlqwtUmCYSJjOeRNIROyMjGKZ@mongodb.railway.internal:27017?authSource=admin
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  redis:
    image: redis:7.4.1-alpine
    ports:
      - '6380:6379'
    healthcheck:
      test: ["CMD-SHELL", "redis-cli", "ping"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - redis-data:/data

  mongo:
    image: mongo
    ports:
      - '27018:27017'
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    volumes:
      - mongo-data:/data

volumes:
  redis-data:
  mongo-data: 
